services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=xz
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=master
    volumes:
      - ./postgres:/var/lib/postgresql/data/
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - psql
    ports:
      - "5437:5432"

volumes:
  postgres:

networks:
  psql:
    driver: bridge